package dev.baranhan.viltrumitecore.client.ironman.hulkbuster;

import net.minecraft.resources.ResourceLocation;

/** Mark 48 art paths (generated by tools/assets/make_hulkbuster.py). */
public final class HulkbusterAssets {
   public static final ResourceLocation BODY = loc("geo/ironman/hulkbuster/mark48.geo.json");
   public static final ResourceLocation FP_ARM = loc("geo/ironman/hulkbuster/fp_arm.geo.json");
   public static final ResourceLocation PARTS = loc("geo/ironman/hulkbuster/parts.geo.json");
   public static final ResourceLocation ANIMATIONS = loc("animations/ironman/hulkbuster/mark48.animation.json");
   public static final ResourceLocation TEXTURE = loc("textures/entity/ironman/hulkbuster.png");
   public static final ResourceLocation GLOW = loc("textures/entity/ironman/hulkbuster_glow.png");

   private HulkbusterAssets() {
   }

   private static ResourceLocation loc(String path) {
      return new ResourceLocation("viltrumitecore", path);
   }
}
