package dev.baranhan.viltrumitecore.client.ironman.mark;

import dev.baranhan.viltrumitecore.client.anim.geo.BakedGeoModel;
import dev.baranhan.viltrumitecore.client.anim.geo.GeoBone;
import dev.baranhan.viltrumitecore.hero.ironman.mark.SuitPart;
import java.util.Locale;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.phys.Vec3;

/**
 * Plate geometry of the mark parts. One Blockbench plate per distinct
 * {@link SuitPart} slice (generated by tools/assets/make_ironman_stage4_visuals.py).
 * The plate is drawn on the body part while it is on, and flies as a world
 * piece before that. Keys mirror {@link SuitPart}: bone, from %, to %, side.
 */
public final class PlateParts {
   private PlateParts() {
   }

   public static String key(SuitPart part) {
      return part.bone().name().toLowerCase(Locale.ROOT) + "_" + Math.round(part.from() * 100.0F) + "_" + Math.round(part.to() * 100.0F) + "_"
         + part.side().name().toLowerCase(Locale.ROOT);
   }

   public static ResourceLocation geo(SuitPart part) {
      return new ResourceLocation("viltrumitecore", "geo/ironman/marks/plates/" + key(part) + ".geo.json");
   }

   /** Rest geometry centre in block units, parsed frame (the frame AnimRenderer draws in). */
   public static Vec3 centre(BakedGeoModel geo) {
      float minX = Float.MAX_VALUE;
      float minY = Float.MAX_VALUE;
      float minZ = Float.MAX_VALUE;
      float maxX = -Float.MAX_VALUE;
      float maxY = -Float.MAX_VALUE;
      float maxZ = -Float.MAX_VALUE;
      for (GeoBone bone : geo.allBones()) {
         for (GeoBone.Cube cube : bone.cubes) {
            for (GeoBone.Quad quad : cube.quads()) {
               for (GeoBone.Vertex v : quad.vertices()) {
                  minX = Math.min(minX, v.x());
                  minY = Math.min(minY, v.y());
                  minZ = Math.min(minZ, v.z());
                  maxX = Math.max(maxX, v.x());
                  maxY = Math.max(maxY, v.y());
                  maxZ = Math.max(maxZ, v.z());
               }
            }
         }
      }

      if (minX > maxX) {
         return Vec3.ZERO;
      }

      return new Vec3((minX + maxX) / 2.0, (minY + maxY) / 2.0, (minZ + maxZ) / 2.0);
   }
}
